import React, { useEffect, useState } from "react";
import { ArrowLeft, Hotel, Plane, Utensils, Sparkles, Wallet, Plus } from "lucide-react";
import { useNavigate, useParams } from "react-router-dom";
import { tripApi, getApiError } from "../services/api";
const money=n=>`₹${Number(n||0).toLocaleString("en-IN")}`;
export default function Budget(){
  const {id}=useParams();const navigate=useNavigate();const [trip,setTrip]=useState(null);const [budget,setBudget]=useState(null);const [form,setForm]=useState({totalBudget:"",transportBudget:"",stayBudget:"",activityBudget:"",mealBudget:""});const [expense,setExpense]=useState({type:"MEAL",amount:"",description:"",expenseDate:new Date().toISOString().slice(0,10)});
  const load=async()=>{try{const [{data:t},{data:b}]=await Promise.all([tripApi.get(id),tripApi.getBudget(id)]);setTrip(t);setBudget(b);setForm({totalBudget:b.totalBudget||"",transportBudget:b.transportBudget||"",stayBudget:b.stayBudget||"",activityBudget:b.activityBudget||"",mealBudget:b.mealBudget||""});}catch(e){alert(getApiError(e));}};useEffect(()=>{load();},[id]);
  if(!trip)return <div className="empty-state"><p>Loading budget...</p></div>;
  const items=[["Transport",Number(budget?.breakdown?.TRANSPORT||0),Plane],["Stay",Number(budget?.breakdown?.STAY||0),Hotel],["Activities",Number(budget?.breakdown?.ACTIVITY||0),Sparkles],["Meals",Number(budget?.breakdown?.MEAL||0),Utensils],["Other",Number(budget?.breakdown?.OTHER||0),Wallet]];
  const save=async e=>{e.preventDefault();try{await tripApi.saveBudget(id,Object.fromEntries(Object.entries(form).map(([k,v])=>[k,Number(v)||0])));await load();alert("Budget saved");}catch(e){alert(getApiError(e));}};
  const addExpense=async e=>{e.preventDefault();try{await tripApi.addExpense(id,{...expense,amount:Number(expense.amount)});setExpense({...expense,amount:"",description:""});await load();}catch(e){alert(getApiError(e));}};
  return <div><div className="page-title"><button className="back-btn" onClick={()=>navigate(`/trips/${id}`)}><ArrowLeft size={18}/></button><div><span className="eyebrow">FINANCIAL OVERVIEW</span><h1>Trip budget</h1><p>Keep your {trip.name} on track.</p></div></div>
    <div className="budget-hero"><div><span>Total budget</span><strong>{money(budget?.totalBudget)}</strong><p>Spent {money(budget?.totalSpent)} · Remaining {money(budget?.remaining)}</p></div><div className="budget-ring"><div><small>SPENT</small><strong>{Math.round(Number(budget?.totalSpent||0)/Math.max(Number(budget?.totalBudget||0),1)*100)}%</strong></div></div></div>
    <div className="budget-layout"><div className="budget-breakdown card"><div className="section-head"><div><h2>Expense breakdown</h2><p>Actual expenses saved in MySQL.</p></div></div>{items.map(([label,value,Icon])=><div className="budget-line" key={label}><div className="budget-label"><span className="budget-icon"><Icon size={17}/></span><div><strong>{label}</strong><span>{Math.round(value/Math.max(Number(budget?.totalSpent||0),1)*100)}% of spent</span></div></div><div className="budget-value"><strong>{money(value)}</strong></div></div>)}
      <form onSubmit={save} className="form-card" style={{marginTop:20}}><h3>Set planned budget</h3><div className="form-grid"><div className="field"><label>Total budget</label><input className="text-input" type="number" value={form.totalBudget} onChange={e=>setForm({...form,totalBudget:e.target.value})}/></div><div className="field"><label>Transport</label><input className="text-input" type="number" value={form.transportBudget} onChange={e=>setForm({...form,transportBudget:e.target.value})}/></div><div className="field"><label>Stay</label><input className="text-input" type="number" value={form.stayBudget} onChange={e=>setForm({...form,stayBudget:e.target.value})}/></div><div className="field"><label>Activities</label><input className="text-input" type="number" value={form.activityBudget} onChange={e=>setForm({...form,activityBudget:e.target.value})}/></div><div className="field"><label>Meals</label><input className="text-input" type="number" value={form.mealBudget} onChange={e=>setForm({...form,mealBudget:e.target.value})}/></div></div><div className="form-actions"><button className="btn btn-primary">Save budget</button></div></form>
      <form onSubmit={addExpense} className="form-card" style={{marginTop:20}}><h3>Add expense</h3><div className="form-grid"><div className="field"><label>Type</label><select className="text-input" value={expense.type} onChange={e=>setExpense({...expense,type:e.target.value})}><option>TRANSPORT</option><option>STAY</option><option>ACTIVITY</option><option>MEAL</option><option>OTHER</option></select></div><div className="field"><label>Amount</label><input className="text-input" type="number" min="0" value={expense.amount} onChange={e=>setExpense({...expense,amount:e.target.value})} required/></div><div className="field"><label>Date</label><input className="text-input" type="date" value={expense.expenseDate} onChange={e=>setExpense({...expense,expenseDate:e.target.value})}/></div><div className="field"><label>Description</label><input className="text-input" value={expense.description} onChange={e=>setExpense({...expense,description:e.target.value})}/></div></div><div className="form-actions"><button className="btn btn-secondary"><Plus size={16}/> Add expense</button></div></form>
    </div><div className="budget-side card"><div className="donut"><div><Wallet size={19}/><strong>{money(budget?.totalSpent)}</strong><span>spent</span></div></div><div className="legend">{items.map(([label,value])=><div key={label}><span>{label}</span><strong>{money(value)}</strong></div>)}</div></div></div>
  </div>;
}
