import React, { useEffect, useState } from "react";
import { Globe2, Mail, Save, Trash2 } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { profileApi, getApiError } from "../services/api";
export default function Profile(){
 const navigate=useNavigate();const [form,setForm]=useState({name:"",email:"",language:"en"});const [loading,setLoading]=useState(true);
 useEffect(()=>{profileApi.get().then(r=>setForm({name:r.data.name||"",email:r.data.email||"",language:r.data.language||"en"})).catch(e=>alert(getApiError(e))).finally(()=>setLoading(false));},[]);
 const save=async e=>{e.preventDefault();try{const {data}=await profileApi.update(form);setForm({name:data.name||"",email:data.email||"",language:data.language||"en"});localStorage.setItem("gt_user",JSON.stringify(data));alert("Profile updated");}catch(e){alert(getApiError(e));}};
 const del=async()=>{if(!confirm("Delete your account? This cannot be undone."))return;try{await profileApi.delete();localStorage.clear();navigate("/login",{replace:true});}catch(e){alert(getApiError(e));}};
 if(loading)return <div className="empty-state"><p>Loading profile...</p></div>;
 return <div className="profile-page"><div className="hero-head"><div><span className="eyebrow">ACCOUNT</span><h1>Profile & settings</h1><p>Manage your profile and travel preferences.</p></div></div><div className="profile-grid"><section className="form-card"><div className="profile-cover"><div className="big-avatar">{form.name?.charAt(0).toUpperCase()||"U"}</div></div><div className="form-card-head"><div><h2>Personal information</h2><p>Keep your traveler profile up to date.</p></div></div><form onSubmit={save}><div className="form-grid"><div className="field"><label>Full name</label><input className="text-input" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/></div><div className="field"><label>Email</label><div className="input-icon"><Mail size={16}/><input value={form.email} onChange={e=>setForm({...form,email:e.target.value})} type="email" required/></div></div><div className="field"><label>Language</label><div className="input-icon"><Globe2 size={16}/><select value={form.language} onChange={e=>setForm({...form,language:e.target.value})}><option value="en">English</option><option value="hi">Hindi</option><option value="gu">Gujarati</option></select></div></div></div><div className="form-actions"><button type="button" className="btn btn-secondary" onClick={del}><Trash2 size={16}/> Delete account</button><button className="btn btn-primary"><Save size={16}/> Save changes</button></div></form></section><aside className="preference-card"><span className="eyebrow">TRAVEL STYLE</span><h3>Make GlobeTrotter yours.</h3><p>Your profile language is stored by the Java backend.</p><div className="chips"><button className="chip active" type="button">🌍 Travel</button><button className="chip" type="button">🏛 Culture</button><button className="chip" type="button">🍜 Food</button><button className="chip" type="button">🏔 Adventure</button></div></aside></div></div>;
}
